extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: https://docs.microsoft.com/en-us/style-guide/capitalization
level: suggestion
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  - ArgoCD
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - OpenSearch
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - Connections
  - Cinchy
  - Cinchy Table
  - Kafka Topic
  - Cinchy Event Broker
  - SuccessFactors
  - Azure Key Vault
