name: Broken link check (Daily)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  broken_link_checker_job:
    runs-on: windows-latest
    env:
      TERM: xterm-256color
    name: Check for broken links
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "\033[31;1;4mHello\033[0m"
      - uses: filiph/linkcheck@master
        with:
          arguments: https://platform.docs.cinchy.com/ --connection-failures-as-warnings --nice
  
          # https://github.com/filiph/linkcheck
