name: Broken link check (Daily)
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: untitaker/hyperlink@0.1.29
        with:
          args: public/ --sources src/