name: Broken link checker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  

jobs:
  hyperlink:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: untitaker/hyperlink@0.1.29
        with:
          args: /Documentation --check-anchors
