name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'https://platform.docs.cinchy.com/'
          exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: -1