name: Broken link checker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@2.0.23
        with:
          arguments: https://platform.docs.cinchy.com/ --connection-failures-as-warnings
