name: Broken link check (Daily)
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - uses: actions/checkout@v3
      - uses: filiph/linkcheck@master
        with:
          arguments: https://platform.docs.cinchy.com/ --connection-failures-as-warnings  
  
          # https://github.com/filiph/linkcheck
