name: Vale linter
on: 
  pull_request:
  workflow_dispatch:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: all
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-check
