name: Vale test
on: [push,pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: all
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-check
