name: Vale test
on: push

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: '["meta-forms/","cinchy-glossary.md"]'
          fail_on_error: true
          reporter: github-check